backend:
  name: github
  branch: main
  repo: w-bastien/w-bastien.github.io
  site_id: c16968bd-1309-47e7-9e60-382905d6b24c
media_folder: "assets/img/uploads"
publish_mode: editorial_workflow
site_url: https://w-bastien.github.io
logo_url: https://w-bastien.github.io/assets/img/branding/avatar.png

collections:
  - name: "Post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: /{{slug}}
    show_preview_links: true
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Publish Date", name: "date", widget: "datetime", required: true }
      - { label: "Categories", name: "categories", widget: "string", required: true }
      - { label: "Tags", name: "tags", widget: "string", required: true }
      - { label: "Featured Image", name: "image", widget: "image", required: false}
      - { label: "Body", name: "body", widget: "markdown", required: true }
      - { label: "Pin article", name: "pin", widget: "boolean", default: false }
      - { label: "Math plugin", name: "math", widget: "boolean", default: false }
      - { label: "Mermaid plugin", name: "mermaid", widget: "boolean", default: false }
      - { label: "Table of content", name: "toc", widget: "boolean", default: true }
      - { label: "Comments", name: "comments", widget: "boolean", default: true }
      
  - label: "Pages"
    name: "pages"
    files:
      - label: "About"
        name: "about"
        file: "_tabs/about.md"
        fields:
          - { label: "Icon", name: "icon", widget: "string", required: true }
          - { label: "Order", name: "order", widget: "number", value_type: "int", required: true }
          - { label: "Body", name: "body", widget: "markdown", required: true }